title: Chintan Zaveri
description: Deep Learning & Machine Learning Engineer in Berlin.
url: https://zaverichintan.github.io
author: Chintan Zaveri
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: legacy
    values:
      sitemap: false
